name: context
on: workflow_dispatch

jobs:
  context:
    runs-on: ubuntu-latest
    steps:
      - name: github context
        run: echo '${{ toJSON(github) }}'
      - name: check github context
        run : |
          echo ${{ github.repository }}
          echo ${{ github.event_name }}
      - name: check github context1111
        run: |
          echo ${{ github.repository }}
          echo ${{ github.event_name }}
      - name: check github context2222
        run: |
          echo ${{ github.repository }}
          echo ${{ github.event_name }}